version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == issuers.github &&
    assertion.repository_owner_id == '93787867' &&
    assertion.repository_id == '1093662716' &&
    assertion.ref == 'refs/heads/main'

scope:
  make-pr:
    rule:
      if: |-
        assertion.workflow_ref.startsWith("abcxyz/github-action-runner/.github/workflows/ci.yml")
    repositories:
      - 'github-action-runner'
    permissions:
      contents: 'write'
      pull_requests: 'write'

  create-tag:
    rule:
      if: |-
        assertion.job_workflow_ref == 'abcxyz/actions/.github/workflows/create-tag.yml@refs/heads/main' &&
        assertion.workflow_ref.startsWith('abcxyz/github-action-runner/.github/workflows/create-tag.yml') &&
        assertion.ref == 'refs/heads/main' &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'github-action-runner'
    permissions:
      contents: 'write'
